# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e6456e0c78e4f16db5c2f172d1a5bdc2f91a12a70c7c3da30594a2ecc4cbd0f32c3c04fa6eb3546ea1a7fa047d1723176e37764cfcf86f56237b9dc4af016e7

test:
  secret_key_base: abbcb32aa548ea0ed913822f062b81b587d3f2d35e8ebec1a9bccc9cc32b2427593e89f7ef10928c08a7d4a8e927e0619d46ba001e56922ff7afe62905254cd2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
